#!/usr/bin/env python
from __future__ import print_function
import sys
import uuid


def create_cf_uuid():
    parts = str(uuid.uuid4()).upper().split('-')
    return '-'.join(parts[:-2] + [''.join(parts[-2:])])

if __name__ == "__main__":
    try:
        num_hits = int(sys.argv[1])
    except:
        num_hits = 1
    for x in range(num_hits):
        print(create_cf_uuid())
