#!/usr/bin/env python
from __future__ import print_function
import uuid


def create_cf_uuid():
    parts = str(uuid.uuid4()).upper().split('-')
    return '-'.join(parts[:-2] + [''.join(parts[-2:])])

if __name__ == "__main__":
    print(create_cf_uuid())
